# Generated by Django 3.2.6 on 2021-09-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('patient_age', models.IntegerField()),
                ('disease', models.CharField(max_length=50)),
                ('ward_number', models.IntegerField()),
                ('payment_detail', models.IntegerField()),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
