# Generated by Django 3.2.6 on 2021-09-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_detail_discharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('patient_age', models.IntegerField()),
                ('disease', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('appointment_date', models.DateField()),
            ],
        ),
    ]
